### ISSUE TITLE
Nothing seems to happen

### ISSUE THREAD

**Issue by CodeByLM** [zkxjzmswkwl/rs3-dlang#2]
i build the project and run loadlib.exe
it gives me the output but nothing seems to happen or show up:
Found a client instance.
C:\Users\User\Desktop\rs3-dlang-main.\DeOppressoLiber.dll
C:\Users\User\Desktop\rs3-dlang-main.\DeOppressoLiber.dll

with debugger attached the only output i get is loaded and unloaded DeOppressoLiber.dll

**Comment by zkxjzmswkwl** [comment]
capstone.dll -> C:\Program Data\Jagex\launcher
